import { Component, inject, signal } from '@angular/core';
import { Functions, httpsCallable } from '@angular/fire/functions';
import { FormsModule } from '@angular/forms';
import { injectMutation } from '@tanstack/angular-query-experimental';
import { RoastCardComponent } from './roast-card/roast-card.component';

interface RoastRequest {
  username: string;
  personality: string;
  intensity: number;
}

@Component({
  imports: [FormsModule, RoastCardComponent],
  selector: 'app-root',
  templateUrl: './app.html',
  styleUrl: './app.scss',
})
export class App {
  functions = inject(Functions);
  isRoastCardOpen = signal(false);
  username = signal('');
  selectedPersonality = signal('public-health-recruiter');
  intensity = signal(3);

  personalities = [
    {
      value: 'public-health-recruiter',
      label: '🏥 Health Tech Recruiter',
      emoji: '🏥',
      description: 'Professional skills matching',
    },
    {
      value: 'epidemiologist',
      label: '📊 Epidemiologist',
      emoji: '📊',
      description: 'Data & analysis focus',
    },
    {
      value: 'global-health-advocate',
      label: '🌍 Global Health Advocate',
      emoji: '🌍',
      description: 'SDG & impact focus',
    },
    {
      value: 'health-systems-analyst',
      label: '⚕️ Systems Analyst',
      emoji: '⚕️',
      description: 'Infrastructure & scale',
    },
    {
      value: 'technical-assessor',
      label: '🔧 Technical Assessor',
      emoji: '🔧',
      description: 'Balanced evaluation',
    },
  ];

  intensityLabels: Record<number, { label: string; emoji: string; color: string }> = {
    1: { label: 'Brief Overview', emoji: '📋', color: 'text-blue-400' },
    2: { label: 'Standard Assessment', emoji: '📝', color: 'text-green-400' },
    3: { label: 'Detailed Analysis', emoji: '🔍', color: 'text-yellow-400' },
    4: { label: 'Comprehensive Report', emoji: '📊', color: 'text-orange-400' },
    5: { label: 'In-Depth Evaluation', emoji: '🎯', color: 'text-purple-400' },
  };

  roastMutations = injectMutation(() => ({
    mutationFn: async (request: RoastRequest) => {
      const callable = httpsCallable<RoastRequest, string>(
        this.functions,
        'githubGrillerFunction',
      );
      const result = await callable(request);
      console.log('Assessment result:', result);
      return result.data;
    },
    onSuccess: (data: string) => {
      console.log('Assessment successful:', data);
      // We don't need to open the modal anymore since we're showing results directly
      // this.isRoastCardOpen.set(true);
    },
    onError: (error: unknown) => {
      console.error('Assessment failed:', error);
      // We removed the alert since we now have inline error display
      // alert('Failed to analyze the profile. Please try again.');
    },
  }));

  submitRoast(): void {
    if (this.username().trim()) {
      this.roastMutations.mutate({
        username: this.username(),
        personality: this.selectedPersonality(),
        intensity: this.intensity(),
      });
    }
  }

  closeRoastCard(): void {
    this.isRoastCardOpen.set(false);
    // Reset the mutation to clear the results and allow re-analysis
    this.roastMutations.reset();
  }

  downloadResults(): void {
    const results = this.roastMutations.data();
    if (!results) return;

    // Clean up the formatting
    const cleanResults = this.cleanResultsFormatting(results);
    
    const blob = new Blob([cleanResults], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `healthtech-assessment-${this.username()}-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  }

  shareResults(): void {
    const results = this.roastMutations.data();
    if (!results) return;

    // Clean up the formatting
    const cleanResults = this.cleanResultsFormatting(results);
    
    const shareText = `HealthTech Assessment for ${this.username()}:\n\n${cleanResults}\n\nGenerated by HealthTech Scout`;
    
    if (navigator.share) {
      navigator.share({
        title: `HealthTech Assessment - ${this.username()}`,
        text: shareText,
        url: window.location.href
      }).catch(() => {
        this.fallbackShare(shareText);
      });
    } else {
      this.fallbackShare(shareText);
    }
  }

  fallbackShare(text: string): void {
    // Copy to clipboard as fallback
    navigator.clipboard.writeText(text).then(() => {
      alert('Results copied to clipboard! You can now paste them anywhere.');
    }).catch(() => {
      // Final fallback - show text in alert
      alert('Share this assessment:\n\n' + text.substring(0, 1000) + '...');
    });
  }

  cleanResultsFormatting(results: string): string {
  // Clean formatting while preserving structure
  let clean = results;
  
  // Remove markdown but keep text content and structure
  const cleaningSteps = [
    // Remove bold and italic markers but keep the text
    { pattern: /\*\*(.*?)\*\*/g, replacement: '$1' },
    { pattern: /\*(.*?)\*/g, replacement: '$1' },
    // Remove other markdown symbols
    { pattern: /`/g, replacement: '' },
    { pattern: /~/g, replacement: '' },
    { pattern: /_/g, replacement: '' },
    // Remove header markers but keep the text
    { pattern: /#{1,6}\s?/g, replacement: '' },
    // Convert links to plain text
    { pattern: /\[(.*?)\]\(.*?\)/g, replacement: '$1' },
  ];

  cleaningSteps.forEach(({ pattern, replacement }) => {
    clean = clean.replace(pattern, replacement);
  });

  // Fix dates
  clean = clean
    .replace(/2024/g, '2025')
    .replace(/2023/g, '2025')
    // Clean up excessive whitespace but preserve paragraphs
    .replace(/\n{3,}/g, '\n\n')
    .replace(/[ ]{2,}/g, ' ')
    .trim();

  return clean;
}

  getIntensityInfo() {
    return this.intensityLabels[this.intensity()] || this.intensityLabels[3];
  }

  getSelectedPersonality() {
    return (
      this.personalities.find((p) => p.value === this.selectedPersonality()) ||
      this.personalities[0]
    );
  }
}